# Generated by Django 5.1.5 on 2025-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
