# Generated by Django 5.1.5 on 2025-04-30 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_type', models.CharField(blank=True, choices=[('S', 'Sale'), ('R', 'Rent')], max_length=200, null=True)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('repair', models.BooleanField(blank=True, null=True)),
                ('mortgage', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('NB', 'New Building'), ('OB', 'Old Building')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flats/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extract', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garage/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GardenHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_type', models.CharField(blank=True, choices=[('S', 'Sale'), ('R', 'Rent')], max_length=200, null=True)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('land_area', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('repair', models.BooleanField(blank=True, null=True)),
                ('mortgage', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('NB', 'New Building'), ('OB', 'Old Building')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garden_house/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extract', models.BooleanField(blank=True, null=True)),
                ('mortgage', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_type', models.CharField(blank=True, choices=[('S', 'Sale'), ('R', 'Rent')], max_length=200, null=True)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('repair', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('H/F', 'House, Flat'), ('BC', 'Business Center')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='office/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
