# Generated by Django 5.1.5 on 2025-04-30 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flatimage',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_images', to='Buildings.flat'),
        ),
        migrations.AddField(
            model_name='garage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garageimage',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_images', to='Buildings.garage'),
        ),
        migrations.AddField(
            model_name='gardenhouse',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardenhouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gardenhouseimage',
            name='garden_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_house_images', to='Buildings.gardenhouse'),
        ),
        migrations.AddField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landimage',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_images', to='Buildings.land'),
        ),
        migrations.AddField(
            model_name='office',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeimage',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_images', to='Buildings.office'),
        ),
    ]
