# Generated by Django 5.1.5 on 2025-05-11 11:27

import Buildings.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeimage',
            name='image',
            field=models.ImageField(upload_to=Buildings.utils.upload_paths.office_image_upload_to),
        ),
    ]
