# Generated by Django 5.1.5 on 2025-05-15 04:43

import Buildings.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0003_alter_officeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimage',
            name='image',
            field=models.ImageField(upload_to=Buildings.utils.upload_paths.flat_image_upload_to),
        ),
        migrations.AlterField(
            model_name='garageimage',
            name='image',
            field=models.ImageField(upload_to=Buildings.utils.upload_paths.garage_image_upload_to),
        ),
        migrations.AlterField(
            model_name='gardenhouseimage',
            name='image',
            field=models.ImageField(upload_to=Buildings.utils.upload_paths.garden_house_image_upload_to),
        ),
        migrations.AlterField(
            model_name='landimage',
            name='image',
            field=models.ImageField(upload_to=Buildings.utils.upload_paths.land_image_upload_to),
        ),
    ]
